version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - 6510:80
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html'
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - '.:/var/www/html'
